# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'SilverOctoSample' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'SwiftyDropbox', '~> 3.0.0'

  # Pods for SilverOctoSample

  target 'SilverOctoSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SilverOctoSampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
